config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get '/search' => 'beers#search', :as => 'search_page'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:show]
  resources :beers do
    collection do
      get 'search'
    end
    resources :reviews
  end
  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/beer.rb
class Beer < ApplicationRecord
  searchkick
  belongs_to :user
  belongs_to :category
  has_many :reviews

  has_attached_file :beer_img, :styles => { :beer_index => "250x350>", :beer_show => "325x475>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :beer_img, :content_type => /\Aimage\/.*\z/

  def self.search(search)
     where("lower(beers.name) LIKE :search OR lower(beers.company) LIKE :search", search: "%#{search.downcase}%").uniq
  end
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :beers
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :beer
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :beers
  has_many :reviews
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/welcome.rb
class Welcome < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/beers_controller.rb
class BeersController < ApplicationController
  before_action :find_beer, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :edit]

  def search
    if params[:search].present?
      @beers = Beer.search(params[:search])
    else
      @beers = Beer.all
    end
  end


  def index
    @botd = Beer.find(Review.maximum('rating'))

    if params[:category].blank?
      @beers = Beer.all.order("created_at DESC")
      #@botd = Beer.all.order("RANDOM()").limit(1)
    else
      @category_id = Category.find_by(name: params[:category]).id
      @beers = Beer.where(:category_id => @category_id).order("created_at DESC")
      #@botd = Beer.where(:category_id => @category_id).order("created_at DESC")
    end
  end

  def show
    if @beer.reviews.blank?
      @average_review = 0
    else
      @average_review = @beer.reviews.average(:rating).round(2)
    end
  end

  def new
    @beer = current_user.beers.build
    @categories = Category.all.map{ |c| [c.name, c.id]}
  end

  def create

    @beer = current_user.beers.build(beer_params)
    @beer.category_id = params[:category_id]
    if @beer.save
      redirect_to root_path
    else
      render 'new'
    end
  end

  def edit
    @categories = Category.all.map{ |c| [c.name, c.id]}
  end

  def update
      @beer = Beer.find(params[:id])
      @beer.category_id = params[:category_id]
      if @beer.update(beer_params)
        redirect_to beer_path(@beer)
      else
        render 'edit'
      end
    end

    def destroy
      @beer.destroy
      redirect_to root_path
    end

  private

    def beer_params
      params.require(:beer).permit(:name, :description, :style, :ABV, :company, :category_id, :beer_img, :lat, :long)
    end

    def find_beer
      @beer = Beer.find(params[:id])
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :find_beer
  before_action :find_review, only: [:edit, :update, :destroy]

  def new
    @review = current_user.reviews.build
    #Review.new
  end

  def create
    @review = current_user.reviews.build(review_params)
    #@review = Review.new(review_params)
    @review.beer_id = @beer.id
    @review.user_id = current_user.id
    if @review.save
      redirect_to beer_path(@beer)
    else
      render 'new'
    end
  end

  def edit
  end



  def update
    if @review.update(review_params)
      @review = Review.find(params[:id])
      redirect_to beer_path(@beer)

    else
      render 'edit'
    end
  end

  def destroy
    @review.destroy
    redirect_to review_path(@beer)
  end

  private

    def review_params
      params.require(:review).permit(:rating, :comment)
    end

    def find_beer
      @beer = Beer.find(params[:beer_id])
    end

    def find_review
      @review = Review.find(params[:id])
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @user_beers = @user.beers
    @user_reviews = @user.reviews
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/beers_helper.rb
module BeersHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/beers/_form.html.erb
<%= simple_form_for @beer, :html => { :multipart => true} do |f| %>
  <%= select_tag(:category_id, options_for_select(@categories), :prompt => "Select a category") %>
<%= f.file_field :beer_img %>
    <%= f.input :name %>
  <%= f.input :description %>
  <%= f.input :style %>
  <%= f.input :ABV %>
  <%= f.input :company %>
  <%= f.input :lat %>
  <%= f.input :long %>
  <%= f.button :submit, :class => 'btn-custom2' %>

<% end %>

app/views/beers/_header.html.erb
<%= form_tag(search_page_path, :method => "get",
    class: 'navbar-form navbar-right') do %>
  <div class="input-group">
    <%= search_field_tag :search, params[:search], placeholder: "Search", class: "form-control" %>
    <div class="input-group-btn">
      <%= button_tag "", :class => 'btn btn-info glyphicon glyphicon-search',:name => nil%>
    </div>
  </div>
<% end %>

app/views/beers/edit.html.erb
<div class="col-md-6 col-md-offset-3">
  <div class="edit-beer-form">

    <h1>Edit Beer</h1>

    <%= simple_form_for @beer, :html => { :multipart => true} do |f| %>
      <%= f.select :category_id, @categories %>
      <%= f.file_field :beer_img %>
      <%= f.input :name, label: "Beer Name" %>
      <%= f.input :description %>
      <%= f.input :style %>
      <%= f.input :ABV %>
      <%= f.input :company %>
      <%= f.input :lat %>
      <%= f.input :long %>
      <%= f.button :submit, :class => 'btn-custom2' %>

    <% end %>
  </div>
</div>

app/views/beers/index.html.erb
<!-- __________________BEER OF THE DAY__________________ -->
<div class="botd">
  <h1 class="mt-4 mb-3">BEER OF THE DAY</h1>
</div>

<!-- __________________BOTD CONTENT__________________ -->
<div class="row beercontainer">
   <div class="col-md-4">
    <!-- __________________BOTD IMAGE__________________ -->
    <a href="/beers/<%= @botd.id %>">
      <%= image_tag @botd.beer_img.url(:beer_index), class: "beer" %>
    </a>
  </div>

  <div class="col-md-6">
    <!-- __________________BOTD NAME AND DESCRIPTION__________________ -->
    <h2><%= @botd.name %></h2>
    <h4><p>Description</p></h4>
    <h6><%= @botd.description %></h6>

  </div>
</div>

<!-- __________________BEER CATEGORIES__________________ -->
<h1 class="current-category"><%= params[:category] %></h1>

<% if @beers.count == 0 %>
  <h2 id="beerscategoryname">No beers here.</h2>
<% else %>

<!-- __________________BEER DATA__________________ -->
  <div class="row">

    <% @beers.each do |beer| %>
    <div class="col-md-3">
      <a href="/beers/<%= beer.id %>">
        <%= image_tag beer.beer_img.url(:beer_index), class: "beer", id: "beer" %>
      </a>
      <div id="beername"><center><strong><%= beer.name %></strong></center></div>
    </div>
    <% end %>
  </div>

<% end %>

app/views/beers/new.html.erb
<div class="col-md-6 col-md-offset-3">
  <div class="new-beer-form">

    <h1>Add Beer</h1>
    <%= render 'form' %>

  </div>
</div>

app/views/beers/search.html.erb
<div class="row">
  <% @beers.each do |beer| %>
  <div class="col-md-3">
    <a href="/beers/<%= beer.id %>">
      <%= image_tag beer.beer_img.url(:beer_index), class: "beer" %>
    </a>
  </div>
  <% end %>
</div>

app/views/beers/show.html.erb
<div class="row">
  <div class="col-md-4">
    <%= image_tag @beer.beer_img.url(:beer_show), class: "beer-show" %>
  </div>

  <div class="col-md-8">
    <div class="beer-info">
      <h2 class="beer-title"><strong><%= @beer.name %></strong></2>
      <h4 class="beer-company"><i><span>by</span> <%= @beer.company %></i></h4>
      <h3 class="avg-rating">Average Rating</h3>
      <div class="average-review-rating" data-score=<%= @average_review %>></div>
      <span class="number-of-reviews">Based on <%= @beer.reviews.count %> reviews</span>
      <h4 >Description</h4>
      <h5 class="beer-desc"><%= @beer.description %></h5>
    </br>
      <h5>Category: <%= @beer.category.name %></h5>
      <h5>Style: <%= @beer.style %></h5>
      <h5>ABV: <%= @beer.ABV %></h5>
    </div>
  </div>
</div>

<div class="row">

  <div class="col-md-4">
    <div class="reviews">
      <!--__________________REVIEWS/RATINGS GO HERE__________________-->
      <h1>Reviews</h1>
        <%= render @beer.reviews %>
      <div>
        <% if user_signed_in? %>
          <%= link_to "Add Review", new_beer_review_path(@beer), class: "btn-custom" %>
        <% end %>
      </div>
    </div>
  </div>

  <div class="col-md-8">
    <div class="beer-on-maps">
      <div style='width: 725px;'>
        <div id="map" style='width: 725px; height: 400px;'></div>
      </div>
    </div>
  </div>

</div>

<div class="links btn-group">
  <%= link_to "Back", root_path, id: "back", class: "btn btn-custom" %>
  <% if user_signed_in? %>
    <% if @beer.user_id == current_user.id %>
      <%= link_to "Edit", edit_beer_path(@beer), class: "btn btn-custom" %>
      <%= link_to "Delete", beer_path(@beer), method: :delete, data: {confirm: "Are you sure?"} , class: "btn btn-custom" %>
    <% end %>
  <% end %>
</div>

<script>
  $('.review-rating').raty({
    readOnly: true,
    score: function(){
      return $(this).attr('data-score');
    },
    path: '/assets/'
  });
</script>

<script>
$('.average-review-rating').raty({
  readOnly: true,
  score: function(){
    return $(this).attr('data-score');
  },
  path: '/assets/'
});
</script>

<script async defer
src="//maps.google.com/maps/api/js?key=AIzaSyBPQk6TTYJrGZhGZV1BUmuc8w3xWWjFz0I&callback=initMap" type="text/javascript">
</script>

<script>
      function initMap() {
        var location = {lat: parseFloat(<%= @beer.lat %>), lng: parseFloat(<%= @beer.long %>)};
        var map = new google.maps.Map(document.getElementById('map'), {
          zoom: 15,
          center: location,
          gestureHandling: 'cooperative'
        });
        var marker = new google.maps.Marker({
          position: location,
          map: map,
          title: 'hello',
        });
      }
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cheers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
    <script src='//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js' type='text/javascript'></script>
    <script src='//underscorejs.org/underscore-min.js' type='text/javascript'></script>

  </head>

  <body>

    <!-- __________________NAVIGATION BAR__________________ -->
    <nav class="navbar navbar-default">
      <div class="container">
        <div class="navbar-header">
            <%= link_to image_tag('logo-26.png'), root_path, :id => "logo" %>
        </div>
          <ul class="nav navnav">
            <li><%= link_to "Home", root_path %></li>
            <li><%= link_to "Beers", beers_path %></li>
            <% if user_signed_in? %>
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
            <% else %>
              <li><%= link_to "Sign Up", new_user_registration_path %></li>
              <li><%= link_to "Log In", new_user_session_path %></li>
            <% end %>

          </ul>

          <ul class="nav navnav navbar-right">
          <%= form_tag search_beers_path, method: :get, class: "navbar-form navbar-right", role: "search" do %>
          <%= text_field_tag :search, params[:search], class: "form_control"%>
              <%= submit_tag "Search", name: nil, class: "btn btn-default" %>
            <% end %>
          </ul>

          <!-- __________________CATEGORIES__________________ -->
          <ul class="nav navnav navbar-right">
            <li class="dropdown">
               <a href="#" data-toggle="dropdown" role="button" aria-expanded="false">Categories<span class="caret"></span></a>
               <ul class="dropdown-menu" role="menu">
                 <%Category.all.each do |category| %>
                  <li class="<%= 'active' if params[:category] == category.name %>">
                    <%= link_to category.name, beers_path(category: category.name), class: "link" %>
                  </li>
                 <% end %>
               </ul>
            </li>

              <% if user_signed_in? %>
            <li><%= link_to "Add Beer", new_beer_path %></li>
              <% end %>
          </ul>
        </div>
      </nav>

      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>

    <div class="container">
      <!-- __________________REST OF SITE GOES HERE (YIELD)__________________ -->
      <%= yield %>
    </div>

    <!-- __________________FOOTER__________________ -->
    <footer class="py-5 col-lg-12">
      <div class="container">
        <div class="row">
          <!-- __________________CONTACT US__________________ -->
          <div class="col-md-4">
            <h3>Contact Details</h3>

            <!-- __________________ADDRESS__________________ -->
            <p>
              201 SE 2nd Avenue
              </br>Gainesville, FL 32601
              </br>
            </p>

            <!-- __________________PHONE__________________ -->
            <p>
              <abbr title="Phone">P</abbr>: (352) CHEERS1 or (352) 243-3771
            </p>

            <!-- __________________EMAIL__________________ -->
            <p>
              <abbr title="Email">E</abbr>:
                <a href="mailto:contact@cheers.com">Contact@Cheers.com</a>
            </p>

            <!-- __________________HOURS__________________ -->
            <p>
              <abbr title="Hours">H</abbr>: Monday - Friday: 9:00 AM to 5:00 PM
            </p>
          </div>
          <!-- __________________BUTTON__________________ -->
          <div class="col-md-8">
            <button type="button" class="btn btn-primary btn-lg" id="button">Contact Us!</button>
          </div>
          <!-- __________________END ROW__________________ -->
        </div>
      </div>
    </footer>

    </body>
</html>

app/views/reviews/_form.html.erb
<%= simple_form_for([@beer, @beer.reviews.build]) do |f| %>

  <div id="rating-form">
    <label>Rating</label>
  </div>
  <%= f.input :comment %>
  <%= f.button :submit, :class => 'btn-custom2' %>

<% end %>

<script>
  $('#rating-form').raty({
    path: '/assets/',
    scoreName: 'review[rating]'
  });
</script>

app/views/reviews/_review.html.erb
<div class="review">
  <h6>On <%= review.created_at%> said <%= review.user.email%>: </h6>
  <div class="review-rating" data-score="<%= review.rating %>"></div>
  <p>
    <%= review.comment %>
  </p>

  <% if user_signed_in? %>
    <% if review.user_id == current_user.id %>

      <div class="links btn-group">

      <%= link_to "Edit", edit_beer_review_path(review.beer, review), class: "btn btn-custom" %>
      <%= link_to "Delete", beer_review_path(review.beer, review), method: :delete, data:{confirm: "Are you sure?"}, class: "btn btn-custom" %>

    </div>

    <% end %>
  <% end %>

</div>

app/views/reviews/edit.html.erb
<div class="col-md-6 col-md-offset-3">
  <div class="edit-review-form">

<h1>Edit Review</h1>

<%= simple_form_for([@beer, @review]) do |f| %>
  <div id="rating-form">
    <label>Rating</label>
  </div>
    <%= f.input :comment %>
    <%= f.button :submit, :class => 'btn-custom2' %>

  <% end %>
  </div>
</div>



<script>
  $('#rating-form').raty({
    path: '/assets/',
    scoreName: 'review[rating]'
  });
</script>

app/views/reviews/new.html.erb
<div class="col-md-6 col-md-offset-3">
  <div class="new-review-form">
    <h1>Write a review</h1>

    <%= render 'form' %>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row img-fluid text-center">
    <img id="userimage" src="https://78.media.tumblr.com/67f2c625e12594a194b1b29a38379438/tumblr_pcv488Eb2o1tgvm9ao1_1280.jpg"/>
  </div>
  <h6 id="username">Username: <%= @user.email %></h6>
</div>

</br>

<div class="container">

  <h3>Account Activity</h3>

  <!--__________________REVIEWS AND ADDED BEERS__________________-->

  <!--__________________REVIEWS__________________-->
  <div class="row">
    <div class="col-md-4 reviewbeer">
      <h4><strong>Recent Reviews</strong></h4>
        <% @user_reviews.each do |review| %>
          <h5 class="beername"><%= link_to review.beer.name, beer_path(review.beer) %></h5>
          <h7>reviewed on <%= review.created_at%></h7>
          <div class="review-rating" data-score="<%= review.rating %>"></div>
          <h6>"<%= review.comment %>"</h6>
          <% if review.user_id == current_user.id %>
            <div class="links btn-group">
              <%= link_to "Edit", edit_beer_review_path(review.beer, review), class:"btn btn-custom" %>
              <%= link_to "Delete", beer_review_path(review.beer, review), method: :delete, data:{confirm: "Are you sure?"}, class: "btn btn-custom"%>
            </div>
          <% end %>
        <% end %>
    </div>

    <!--__________________ADDED BEERS__________________-->
    <div class="col-md-6 addbeer">
      <h4><strong>Added Beers</strong></h4>
      <% @user_beers.each do |beer| %>
        <h5 class="beername"><%= link_to beer.name, beer_path(beer) %></h5>
        <h7>created on <%=beer.created_at%></h7>
        <% if beer.user_id == current_user.id %>

      </br>
          <%= link_to "Edit", edit_beer_path(beer), class: "btn btn-custom" %>
          <%= link_to "Delete", beer_path(beer), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-custom"%>

        <% end %>
      <% end %>

    </div>
  </div>

  <!--__________________RECOMMENDED BEERS__________________-->
  <div class="row recommendbeer">
    <div class="col-lg-12">
      <h4><strong>Recommended Beers</strong></h4>
      <% @user_reviews.each do |review| %>
        <% if review.rating == Review.maximum('rating') %>
          <% @beer = Beer.find(review.beer_id) %>
          <h6>Based on your choice of <i><%= @beer.name %>:</i></h6>
            <% Beer.all.each do |beer| %>
              <% if beer.category_id == @beer.category_id or beer.ABV == @beer.ABV %>
                <% if beer.user_id != @beer.user_id %>
                  <div class="beercard">
                    <a href="/beers/<% beer.id %>">
                      <%= image_tag beer.beer_img.url(:beer_index), class: "beer" %>
                    </a>
                  </div>
                <% end %>
              <% end %>
            <% end %>
          <% end %>
        <% end %>

  <!--__________________SCRIPTS__________________-->
      <script>
        $('.review-rating').raty ({
          readOnly: true,
          score: function(){
            return $(this).attr('data-score');
          },
          path: '/assets/'
        });
      </script>

    </div>
  </div>

</div>